export const SET_CORPINFO = 'SET_CORPINFO'
export const SET_CUSTOMINFO = 'SET_CUSTOMINFO'
export const SET_POORINFO = 'SET_POORINFO'
export const SET_PRODUCTBATCH_TRACENODEINFO = 'SET_PRODUCTBATCH_TRACENODEINFO'
export const SET_BLOCK_CHAININFO = 'SET_BLOCK_CHAININFO'
export const SET_ANT_FAKEINFO = 'SET_ANT_FAKEINFO'

